tests/conftest.py, tests/instruments/test_ship_underwater_st.py, virtual_ship/instruments/ship_underwater_st.py, virtual_ship/sailship.py, virtual_ship/spacetime.py
- Implemented test for ship underwater st. Other tests will follow, but let's review this one so we agree on how to test.
- Refactored and made ship underwater st work so it passes the test
=> Ship underwater st test

tests/instruments/test_ctd.py, tests/test_sailship.py, virtual_ship/instruments/ctd.py, virtual_ship/sailship.py
* Cleaned up CTD
* Wrote test for CTD
Fields varying with time are not tested, as it's quite tricky to predict the expected observations.
There is also an issue currently, where the simulation always goes over the complete fieldset. Have to check if we can tall Parcels to stop simulating when all particles are done, and maybe skip over parts where no particles have been deployed yet.
=> Ctd cleanup and test

virtual_ship/location.py, virtual_ship/virtual_ship_config.py
=> move lat lon test into location class

tests/test_sailship.py, virtual_ship/sailship.py
verified when checking the waypoints, not during simulation
closes #25
=> verify waypoints are on water

meta.yaml, pyproject.toml
- Add meta.yaml for conda. Very minimal but it builds the package. Does not provide development environment whatsoever, but Emma and me agreed it's not worth the effort to set that up when development with pip works fine.
- Remove old dependencies from pyproject.toml
=> Conda recipe

tests/test_sailship.py, tests/test_schedule.py, virtual_ship/__init__.py, virtual_ship/costs.py, virtual_ship/sailship.py, virtual_ship/schedule.py, virtual_ship/virtual_ship_config.py
=> 52 schedule to and from yaml

src/virtualship/expedition/input_data.py
As Parcels [v3.1.0](https://github.com/OceanParcels/Parcels/releases/v3.1.0) has moved from `grid.depth` to `grid._depth`, the code for VirtualShip is now broken. 
This PR fixes that, although a more proper implementation would be to add a `grid.negate_depth()` method to Parcels itself?
=> Using private grid._depth for negating depth

environment.yml, pyproject.toml, src/virtualship/expedition/input_data.py
API changes and warning changes in Parcels v.3.1.0 have caused some breakage in virtualship. Pinning to Parcels `<3.1.0` until we have a `.negate_depth` method in parcels, and the warning is fixed. After that is done we would need to pin to >3.1.0.
Changes:
- Revert #75
- Pin parcels<3.1.0
Related:
https://github.com/conda-forge/virtualship-feedstock/pull/1
=> pin parcels<3.1.0

README.md, codecov.yml, docs/contributing.md, src/virtualship/instruments/__init__.py, src/virtualship/instruments/xbt.py, tests/instruments/test_xbt.py
This PR introduces a new instrument simulation, `xbt.py`, located in the `instruments/` directory. The `xbt.py` file is modeled on `ctd.py` and is designed to simulate data collection for Expendable Bathythermographs (XBTs), which capture water temperature at varying depths.
- **New Instrument**: Added `xbt.py` to `instruments/` directory for XBT data simulation.
- **Test**: Added `test_xbt.py` based on `test_ctd.py`
- **Init Update**: Modified `instruments/__init__.py` to include `xbt.py` in the module exports.
- **Status**: Ready to review.
- Update documentation to reflect the addition of the XBT instrument.
=> Add XBT instrument simulation based on CTD

README.md, src/virtualship/cli/commands.py
I thought it would be nice to add a contributing section like that seen in [parcels README](https://github.com/OceanParcels/parcels?tab=readme-ov-file#contributors)
=> Add contributing section and update README help messages

docs/classroom-surf-environment.yml
SURF Research Cloud Jupyter instances can be given custom kernels/environments by:
- providing a config in a public git repo
- providing repo URL, and config filepath when initially creating the instances via the dashboard
- [their docs](https://gitlab.com/rsc-surf-nl/plugins/plugin-custom-packages/-/blob/main/README.md) for more info
This PR adds this config file.
What additional conda packages do you think students would need for analysis @ammedd ?
Currently have:
```
- python=3.10
- virtualship
- numpy
- scipy
- pandas
- ipykernel
```
=> SURF Research Cloud config

docs/classroom-surf-environment.yml
- Update kernel name
- Add colab dependency 
xref #104
=> Update SURF config

src/virtualship/cli/_fetch.py, src/virtualship/expedition/do_expedition.py
=> Remove instruments from config if not in schedule

src/virtualship/cli/commands.py, src/virtualship/static/schedule.yaml
Only default data was downloaded, added argo and drifter with buffers around it
=> add drifter + argo data dowload (quick fix, can be made nicer)

src/virtualship/instruments/argo_float.py, src/virtualship/instruments/drifter.py
=> Providing verbose progress for drifters and argo floats

pyproject.toml, src/virtualship/expedition/ship_config.py, src/virtualship/utils.py, tests/expedition/test_simulate_schedule.py
- Closes #136
Copied a test from https://github.com/OceanParcels/virtualship/commit/99955d7d231b76ef7dee9b51b776b5812c9fb6e4 as mentioned in #136.
The problem was that there was no deserialisation (i.e., "field validation" in pydantic terms) of the minutes to the timedelta objects (serialisation = model -> file, validation = file -> model). By default it treated the float as seconds.
Were there any other fields that are in minutes besides `ADCPConfig.period`, `CTDConfig.stationkeeping_time`, `ShipUnderwaterSTConfig.period`, and `DrifterConfig.lifetime` @erikvansebille  and @ammedd ?
Careful when merging this into [ship_spped_in_knots](https://github.com/OceanParcels/virtualship/compare/ship_spped_in_knots) to make sure the new Drifter.period also gets a deserialisation method like …
=> Add deserialisation (i.e., field validators) for minute fields

src/virtualship/expedition/do_expedition.py
Useful for e.g. sailing with ADCP turned on
- Closes #xxxx
=> Adding support for waypoints without instruments

src/virtualship/cli/commands.py, src/virtualship/expedition/do_expedition.py, src/virtualship/static/schedule.yaml, src/virtualship/utils.py, tests/expedition/expedition_dir/schedule.yaml
=> Supporting list of instruments in yaml

src/virtualship/expedition/simulate_schedule.py
This PR fixes two bugs that make the ship finish too quickly.
1. The conversion from kots/hr to m/s was the wrong way around, leading to ~4x higher ship speeds
2. The ship wouldn't wait at the waypoint until it was planned to be there, if it arrived too early
=> Fixing bugs where ship went too fast

src/virtualship/utils.py, tests/test_mfp_to_yaml.py
=> Add support for csv files as input

.github/CONTRIBUTING.md, README.md, pyproject.toml
The documentation domain for VirtualShip has moved to `https://virtualship.readthedocs.io/`
- Closes None
=> Update doc links

src/virtualship/cli/_fetch.py
=> Prevent fetch from downloading unnecessary data and skipping data download for certain instruments

.github/workflows/ci.yml, environment.yml, src/virtualship/expedition/do_expedition.py, src/virtualship/expedition/input_data.py, src/virtualship/expedition/schedule.py, src/virtualship/expedition/simulate_measurements.py
- xref #180
This PR:
- Adds mypy tooling (as conda dependency, and as github actions workflow)
- Does some mypy fixes
Note that this PR doesn't fix all mypy errors. I don't think fixing all mypy errors is a priority (especially since some will likely evaporate after doing a bit of a refactor of the offending code), but I think its a good thing to keep an eye out so we can gradually work towards no errors.
=> Mypy tooling and some mypy fixes

environment.yml, pyproject.toml, src/virtualship/expedition/do_expedition.py, src/virtualship/expedition/simulate_measurements.py, src/virtualship/instruments/__init__.py, src/virtualship/models/schedule.py, src/virtualship/utils.py, tests/expedition/test_do_expedition.py
This PR is an updated and re-imagined version of what I was trying to achieve in #188 (now closed). This version filters out Parcels INFO log messages (to avoid flooding the log) and introduces a yaspin spinner for the output messages. 
Print statements as the expedition runs are also updated to guide the user through what's happening at each step. Tests updated as well.
=> Updated logging (informative log messages, spinners for progress, suppressing Parcels info messages)

.github/PULL_REQUEST_TEMPLATE.md, design-doc.md, docs/contributing/index.md
I've translated our meeting notes to a document `./design-doc.md` . Please use GitHub's review functionality to discuss anything that needs to be clarified before merging.
- Closes #187
=> Add design document

environment.yml, pyproject.toml, tests/make_realistic/test_ctd_make_realistic.py
Updated copernicusmarine dependency to v2.2.2, which fixes the bug raised in #198. 
`virtualship fetch` is now working again!
=> Update to copernicusmarine v2.2.2

docs/index.md
As raised in #203, the header in the VirtualShip docs has a link to the Parcels website, whereas a link to the VirtualShip website makes more sense. This PR swaps the Parcels link for VirtualShip.
=> Change docs header link to VirtualShip website
